language: php

php:
- 7.2

before_script:
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate

before_install:
- mysql -e 'CREATE DATABASE testing;'

install:
- cp .env.travis .env

script:
- phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

after_success: sh -c "if [ ! -z ${COVERAGE+x} ]; then php vendor/bin/coveralls; fi"

services:
- mysql

cache:
  directories:
  - node_modules
  - vendor

notifications:
  email: false